version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goomer
      MYSQL_DATABASE: goomer
    ports:
      - "3309:3306"

  app:
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: goomer
      DB_NAME: goomer
      PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
